name: Scala

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: [ 2.13.5, 3.0.0-RC3 ]
        platform: [JVM, JS, Native]
        exclude:
          - scala: 3.0.0-RC3
            platform: native
    runs-on: ubuntu-20.04
    name: Scala CI
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.14
      - name: Test with Coverage
        if: matrix.scala == '2.13.5' && matrix.platform == 'JVM'
        run: sbt ++${{ matrix.scala }} coverage testJVM coverageAggregate
      - name: Test
        if: !(matrix.scala == '2.13.5' && matrix.platform == 'JVM')
        run: sbt ++${{ matrix.scala }} test${{ matrix.platform }}
      - name: Format and Lint
        if: matrix.scala == '2.13.5' && matrix.platform == 'JVM'
        run: sbt ++${{ matrix.scala }} scalafmtCheckAll scalafmtSbtCheck 'scalafixAll --check'
      - uses: codecov/codecov-action@v1
        if: matrix.scala == '2.13.5' && matrix.platform == 'JVM'
