name: Scala

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: [ 2.13.5, 3.0.0-RC3 ]
    runs-on: ubuntu-20.04
    name: Scala CI
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.14
      - name: Test with Coverage
        if: matrix.scala == '2.13.5'
        run: sbt ++${{ matrix.scala }} coverage test coverageAggregate
      - name: Test
        if: matrix.scala == '3.0.0-RC3'
        run: sbt ++${{ matrix.scala }} test
      - name: Format and Lint
        if: matrix.scala == '2.13.5'
        run: sbt ++${{ matrix.scala }} scalafmtCheckAll scalafmtSbtCheck 'scalafixAll --check'
      - uses: codecov/codecov-action@v1
